apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ticketing-auth-service
      context: ./
      docker:
        dockerfile: be.dockerfile
        buildArgs:
          FOLDER: auth
      sync:
        manual:
          - src: 'auth/src/**/*.ts'
            dest: .
    # - image: ticketing-client-service
    #   context: ./
    #   docker:
    #     dockerfile: client.dockerfile
    #   sync:
    #     manual:
    #       - src: 'client/**/*{.ts,.tsx}'
    #         dest: .
