apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ticketing-auth-service
      context: ./
      docker:
        dockerfile: be.dockerfile
        buildArgs:
          FOLDER: auth
      sync:
        manual:
          - src: 'auth/src/**/*.ts'
            dest: .
    - image: ticketing-client-service
      context: ./
      docker:
        dockerfile: client.dockerfile
      sync:
        manual:
          - src: 'client/**/*{.ts,.tsx}'
            dest: .
    - image: ticketing-service
      context: ./
      docker:
        dockerfile: be.dockerfile
        buildArgs:
          FOLDER: ticketing
    - image: orders-service
      context: ./
      docker:
        dockerfile: be.dockerfile
        buildArgs:
          FOLDER: orders
    - image: ticketing-expiration-service
      context: ./
      docker:
        dockerfile: be.dockerfile
        buildArgs:
          FOLDER: expiration
    - image: ticketing-payment-service
      context: ./
      docker:
        dockerfile: be.dockerfile
        buildArgs:
          FOLDER: payments
      sync:
        manual:
          - src: 'payments/src/**/*.ts'
            dest: .
