POST http://ticketing.dev/api/users/sign-up
Content-Type: application/json

{
    "email":"samyak@mail.com",
    "password":"password"
}

###
POST http://ticketing.dev/api/users/sign-in
Content-Type: application/json

{
    "email":"samyak@mail.com",
    "password":"password"
}

###
GET http://ticketing.dev/api/tickets
Content-Type: application/json


###
POST http://ticketing.dev/api/tickets
Content-Type: application/json

{
    "title":"nginx",
    "price":400
}


###
PATCH http://ticketing.dev/api/tickets/65cb8ecf132f1ca5783e1c3b
Content-Type: application/json

{
    "title":"updated",
    "price":20
}

###
POST http://ticketing.dev/api/orders
Content-Type: application/json

{
    "ticketId":"6607dbae8b5d31cb0f13710d"
}


###
POST http://ticketing.dev/api/payments
Content-Type: application/json

{
    "orderId":"6607dbb54eae6c7cccb72f6b",
    "token":"tok_visa"
}
