POST http://ticketing.dev/api/users/sign-up
Content-Type: application/json

{
    "email":"samyak@mail.com",
    "password":"password"
}

###
POST http://ticketing.dev/api/users/sign-in
Content-Type: application/json

{
    "email":"samyak@mail.com",
    "password":"password"
}

###
GET http://ticketing.dev/api/tickets
Content-Type: application/json


###
POST http://ticketing.dev/api/tickets
Content-Type: application/json

{
    "title":"new ticket",
    "price":400
}


###
PATCH http://ticketing.dev/api/tickets/65cb8ecf132f1ca5783e1c3b
Content-Type: application/json

{
    "title":"updated",
    "price":20
}

###
POST http://ticketing.dev/api/orders
Content-Type: application/json

{
    "ticketId":"6602327e7330a69b387887fc"
}
