apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
  
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: ticketing-payment-service
          env:
            - name: FOLDER
              value: payments
            
            - name: MONGODB_URI
              value: mongodb://payments-mongo-srv:27017/payments 

    
            - name: NATS_URL
              value: http://nats-srv:4222

            - name: NATS_CLUSTER_ID
              value: ticketing

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: JWT_SERCRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-public
                  key: public

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: secret
          ports:
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
