apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing
  template:
    metadata:
      labels:
        app: ticketing
    spec:
      containers:
        - name: ticketing
          image: ticketing-auth-service
          env:
            - name: FOLDER
              value: ticketing

            - name: JWT_SERCRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-srv
spec:
  selector:
    app: ticketing
  
  ports:
    - name: ticketing
      protocol: TCP
      port: 3000
      targetPort: 3000
